name: Terraform validate and format check

on:
  workflow_call: # Make the workflow callable by other workflows
    secrets:
      AZURE_CLIENT_ID: {}
      AZURE_CLIENT_SECRET: {}
      AZURE_SUBSCRIPTION_ID: {}
      AZURE_TENANT_ID: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      WORKING_DIR: ./deployments/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8

      - name: Terraform init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform fmt check
        run: terraform fmt -check -recursive
        continue-on-error: false
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform validate
        run: terraform validate
        working-directory: ${{ env.WORKING_DIR }}
